version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - $PWD/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
  node:
    image: node:16
    container_name: node
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    volumes:
      - $PWD/node/:/usr/src/app
    expose:
      - "8080"
    command: "npm start"
    networks:
      - internal
networks:
  internal:
